import { NextResponse } from 'next/server'
import { requireBusinessContext } from '@/lib/supabase-server'
import { createAdminClient } from '@/lib/supabase-admin'
import { apiError } from '@/lib/http-errors'
import { normalizePhone } from '@/lib/phone'

export async function POST(request:Request){
  let createdUserId:string|undefined
  try{const {businessId}=await requireBusinessContext(['OWNER','ADMIN']);const body=await request.json() as {email?:string;displayName?:string;phone?:string;branchId?:string|null;color?:string;commissionPercent?:number;specialtyIds?:string[];serviceIds?:string[]};if(!body.email||!body.displayName)return NextResponse.json({error:'Nombre y correo son obligatorios'},{status:400});const phone=body.phone?.trim()?normalizePhone(body.phone):null;if(body.phone?.trim()&&!phone)return NextResponse.json({error:'Teléfono inválido'},{status:400});const admin=createAdminClient();const {data:link,error:authError}=await admin.auth.admin.generateLink({type:'invite',email:body.email.toLowerCase(),options:{redirectTo:`${process.env.NEXT_PUBLIC_APP_URL}/auth/callback`}});if(authError)throw authError;createdUserId=link.user.id;const {data:member,error:memberError}=await admin.from('business_members').insert({business_id:businessId,user_id:createdUserId,role:'PROFESSIONAL'}).select().single();if(memberError)throw memberError;const {data:professional,error:professionalError}=await admin.from('professionals').insert({business_id:businessId,branch_id:body.branchId??null,member_id:member.id,display_name:body.displayName.trim(),phone,color:body.color??'#5b3df5',commission_percent:body.commissionPercent??0}).select().single();if(professionalError)throw professionalError;if(body.specialtyIds?.length)await admin.from('professional_specialties').insert(body.specialtyIds.map(specialty_id=>({professional_id:professional.id,specialty_id})));if(body.serviceIds?.length)await admin.from('professional_services').insert(body.serviceIds.map(service_id=>({professional_id:professional.id,service_id})));return NextResponse.json({professional,inviteLink:link.properties.action_link},{status:201})}catch(error){if(createdUserId){try{await createAdminClient().auth.admin.deleteUser(createdUserId)}catch{}}return apiError(error)}
}
