'use client'
import { useEffect, useState } from 'react'
import { X } from 'lucide-react'
import { dateKeyInZone, formatTimeInZone, zonedDayRange } from '@/lib/timezone'

type Catalog={services:Array<{id:string;name:string;price:number}>;professionals:Array<{id:string;display_name:string}>;branches:Array<{id:string;name:string}>}
type Client={id:string;full_name:string;phone:string|null}
type Slot={professional_id:string;professional_name:string;service_start:string;service_end:string;quoted_price:number}

export function NewAppointmentModal({onClose,onCreated,timezone='America/Santiago'}:{onClose:()=>void;onCreated:()=>void;timezone?:string}){
  const [catalog,setCatalog]=useState<Catalog|null>(null),[clients,setClients]=useState<Client[]>([]),[serviceId,setServiceId]=useState(''),[clientId,setClientId]=useState(''),[date,setDate]=useState(dateKeyInZone(new Date(),timezone)),[slots,setSlots]=useState<Slot[]>([]),[slot,setSlot]=useState<Slot|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('')
  useEffect(()=>{Promise.all([fetch('/api/admin/catalog').then(r=>r.json()),fetch('/api/admin/clients').then(r=>r.json())]).then(([c,p])=>{setCatalog(c);setClients(p.clients??[])})},[])
  async function search(){setError('');setSlot(null);const {from,until}=zonedDayRange(date,timezone);const response=await fetch('/api/admin/slots',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({serviceId,from,until})});const data=await response.json();if(!response.ok){setError(data.error??'No se pudo buscar');return}setSlots(data.slots??[])}
  async function create(){if(!slot||!clientId||!catalog)return;setLoading(true);setError('');const response=await fetch('/api/admin/agenda',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({branchId:catalog.branches[0]?.id??null,clientId,professionalId:slot.professional_id,serviceId,desiredStart:slot.service_start})});const data=await response.json();if(response.status===409){setError('Ese horario acaba de ocuparse. Busca nuevamente.');setSlot(null);await search();setLoading(false);return}if(!response.ok){setError(data.error??'No se pudo reservar');setLoading(false);return}onCreated();onClose()}
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><div className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="text-xl font-black">Nueva reserva</h2><p className="text-sm text-[#736f83]">La hora se revalida al confirmar.</p></div><button aria-label="Cerrar" onClick={onClose} className="rounded-lg p-2 hover:bg-black/5"><X/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Cliente<select value={clientId} onChange={e=>setClientId(e.target.value)} className="mt-2 w-full rounded-xl border p-3"><option value="">Seleccionar</option>{clients.map(c=><option key={c.id} value={c.id}>{c.full_name}</option>)}</select></label><label className="text-sm font-semibold">Servicio<select value={serviceId} onChange={e=>{setServiceId(e.target.value);setSlots([]);setSlot(null)}} className="mt-2 w-full rounded-xl border p-3"><option value="">Seleccionar</option>{catalog?.services?.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="text-sm font-semibold">Fecha<input type="date" min={dateKeyInZone(new Date(),timezone)} value={date} onChange={e=>{setDate(e.target.value);setSlots([])}} className="mt-2 w-full rounded-xl border p-3"/></label><button disabled={!serviceId} onClick={search} className="self-end rounded-xl border border-[#5b3df5] p-3 font-bold text-[#5b3df5] disabled:opacity-40">Buscar disponibilidad</button></div>{slots.length>0&&<div className="mt-5"><p className="mb-2 text-sm font-bold">Horas realmente disponibles</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{slots.map(s=><button key={`${s.professional_id}-${s.service_start}`} onClick={()=>setSlot(s)} className={`rounded-xl border p-3 text-left text-sm ${slot===s?'border-[#5b3df5] bg-violet-50':''}`}><b>{formatTimeInZone(s.service_start,timezone)}</b><small className="block truncate text-[#736f83]">{s.professional_name}</small></button>)}</div></div>}{slots.length===0&&serviceId&&<p className="mt-5 text-sm text-[#736f83]">Selecciona “Buscar disponibilidad”.</p>}{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={!slot||!clientId||loading} onClick={create} className="mt-6 w-full rounded-xl bg-[#5b3df5] py-3 font-bold text-white disabled:opacity-40">{loading?'Confirmando…':'Confirmar reserva'}</button></div></div>
}
