'use client'

import { PageHeader } from '@/components/PageHeader'
import { ClientRescheduleModal } from '@/components/ClientRescheduleModal'
import { useCallback, useEffect, useState } from 'react'
import { formatInZone } from '@/lib/timezone'
import {CalendarPlus,CheckCircle2} from 'lucide-react'

type Appointment={id:string;status:string;service_period:string;professional:{id:string;display_name:string}|null;service:{id:string;name:string}|null;branch:{name:string;address?:string|null}|null}
const rangeStart=(range:string)=>new Date(range.replace(/[\[\]()"]/g,'').split(',')[0])
const rangeDates=(range:string)=>range.replace(/[\[\]()"]/g,'').split(',').map(value=>new Date(value))
const icsStamp=(date:Date)=>date.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z')
const icsClean=(value:string)=>value.replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;')

export default function ClientBookings(){
  const [appointments,setAppointments]=useState<Appointment[]>([]),[timezone,setTimezone]=useState('America/Santiago'),[settings,setSettings]=useState<Record<string,any>>({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[rescheduling,setRescheduling]=useState<Appointment|null>(null)
  const load=useCallback(()=>fetch('/api/client/appointments',{cache:'no-store'}).then(async response=>{if(!response.ok)throw new Error();return response.json()}).then(data=>{setAppointments(data.appointments??[]);setTimezone(data.timezone??'America/Santiago');setSettings(data.settings??{});setError('')}).catch(()=>setError('No se pudieron cargar tus reservas.')).finally(()=>setLoading(false)),[])
  useEffect(()=>{load()},[load])
  async function confirm(id:string){const response=await fetch('/api/client/appointments',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({appointmentId:id,action:'confirm'})});const data=await response.json();setMessage(response.ok?'Reserva confirmada.':data.error??'No se pudo confirmar');if(response.ok)load()}
  async function cancel(id:string){if(!window.confirm('¿Confirmas la cancelación? El negocio recibirá el cambio y el horario quedará libre.'))return;const response=await fetch('/api/client/appointments',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({appointmentId:id,action:'cancel'})});const data=await response.json();setMessage(response.ok?'Reserva cancelada.':data.error??'No se pudo cancelar');if(response.ok)load()}
  function addCalendar(appointment:Appointment){const [start,end]=rangeDates(appointment.service_period),summary=`${appointment.service?.name??'Reserva'} con ${appointment.professional?.display_name??'profesional'}`;const content=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Agen//Reserva//ES','BEGIN:VEVENT',`UID:${appointment.id}@agen`,`DTSTAMP:${icsStamp(new Date())}`,`DTSTART:${icsStamp(start)}`,`DTEND:${icsStamp(end)}`,`SUMMARY:${icsClean(summary)}`,`LOCATION:${icsClean(appointment.branch?.address??appointment.branch?.name??'')}`,'BEGIN:VALARM','TRIGGER:-PT2H','ACTION:DISPLAY','DESCRIPTION:Tu reserva comienza en 2 horas','END:VALARM','END:VEVENT','END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([content],{type:'text/calendar;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download='reserva-agen.ics';link.click();URL.revokeObjectURL(url)}
  return <>{rescheduling&&<ClientRescheduleModal appointment={rescheduling} timezone={timezone} onClose={()=>setRescheduling(null)} onUpdated={()=>{setMessage('Reserva reagendada.');load()}}/>}<PageHeader title="Mis reservas" description="Próximas atenciones e historial."/>{message&&<p className="mb-4 rounded-xl bg-violet-50 p-3 text-sm text-violet-800">{message}</p>}{error&&<p className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="space-y-3">{appointments.map(appointment=>{const start=rangeStart(appointment.service_period),open=!['CANCELLED','COMPLETED','NO_SHOW','IN_PROGRESS'].includes(appointment.status);return <div key={appointment.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><b>{appointment.service?.name??'Servicio'} · {formatInZone(start,timezone,{dateStyle:'long',timeStyle:'short'})}</b><p className="text-sm text-[#736f83]">{appointment.professional?.display_name} · {appointment.branch?.name}</p></div><div className="flex flex-wrap items-center gap-2"><span className="h-fit rounded-full bg-violet-50 px-3 py-1 text-xs font-bold text-violet-700">{appointment.status}</span>{appointment.status==='PENDING'&&<button onClick={()=>void confirm(appointment.id)} className="inline-flex items-center gap-1 rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700"><CheckCircle2 size={14}/>Confirmar</button>}{open&&<button onClick={()=>addCalendar(appointment)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-bold text-[#5b3df5]"><CalendarPlus size={14}/>Calendario</button>}{open&&settings.allow_client_reschedule!==false&&<button onClick={()=>setRescheduling(appointment)} className="rounded-lg border px-3 py-2 text-xs font-bold text-[#5b3df5]">Reagendar</button>}{open&&settings.allow_client_cancel!==false&&<button onClick={()=>cancel(appointment.id)} className="rounded-lg border px-3 py-2 text-xs font-bold text-red-600">Cancelar</button>}</div></div></div>})}{!loading&&appointments.length===0&&<div className="rounded-2xl border bg-white p-8 text-center text-[#736f83]">Aún no tienes reservas.</div>}{loading&&<p className="rounded-2xl border bg-white p-8 text-center text-sm text-[#736f83]">Cargando reservas…</p>}</div></>
}
