'use client'

import { PageHeader } from '@/components/PageHeader'
import { ClientRescheduleModal } from '@/components/ClientRescheduleModal'
import { useCallback, useEffect, useState } from 'react'
import { formatInZone } from '@/lib/timezone'

type Appointment={id:string;status:string;service_period:string;professional:{id:string;display_name:string}|null;service:{id:string;name:string}|null;branch:{name:string}|null}
const rangeStart=(range:string)=>new Date(range.replace(/[\[\]()"]/g,'').split(',')[0])

export default function ClientBookings(){
  const [appointments,setAppointments]=useState<Appointment[]>([]),[timezone,setTimezone]=useState('America/Santiago'),[settings,setSettings]=useState<Record<string,any>>({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[rescheduling,setRescheduling]=useState<Appointment|null>(null)
  const load=useCallback(()=>fetch('/api/client/appointments',{cache:'no-store'}).then(async response=>{if(!response.ok)throw new Error();return response.json()}).then(data=>{setAppointments(data.appointments??[]);setTimezone(data.timezone??'America/Santiago');setSettings(data.settings??{});setError('')}).catch(()=>setError('No se pudieron cargar tus reservas.')).finally(()=>setLoading(false)),[])
  useEffect(()=>{load()},[load])
  async function cancel(id:string){if(!window.confirm('¿Confirmas la cancelación? El negocio recibirá el cambio y el horario quedará libre.'))return;const response=await fetch('/api/client/appointments',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({appointmentId:id,action:'cancel'})});const data=await response.json();setMessage(response.ok?'Reserva cancelada.':data.error??'No se pudo cancelar');if(response.ok)load()}
  return <>{rescheduling&&<ClientRescheduleModal appointment={rescheduling} timezone={timezone} onClose={()=>setRescheduling(null)} onUpdated={()=>{setMessage('Reserva reagendada.');load()}}/>}<PageHeader title="Mis reservas" description="Próximas atenciones e historial."/>{message&&<p className="mb-4 rounded-xl bg-violet-50 p-3 text-sm text-violet-800">{message}</p>}{error&&<p className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="space-y-3">{appointments.map(appointment=>{const start=rangeStart(appointment.service_period),open=!['CANCELLED','COMPLETED','NO_SHOW','IN_PROGRESS'].includes(appointment.status);return <div key={appointment.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><b>{appointment.service?.name??'Servicio'} · {formatInZone(start,timezone,{dateStyle:'long',timeStyle:'short'})}</b><p className="text-sm text-[#736f83]">{appointment.professional?.display_name} · {appointment.branch?.name}</p></div><div className="flex flex-wrap items-center gap-2"><span className="h-fit rounded-full bg-violet-50 px-3 py-1 text-xs font-bold text-violet-700">{appointment.status}</span>{open&&settings.allow_client_reschedule!==false&&<button onClick={()=>setRescheduling(appointment)} className="rounded-lg border px-3 py-2 text-xs font-bold text-[#5b3df5]">Reagendar</button>}{open&&settings.allow_client_cancel!==false&&<button onClick={()=>cancel(appointment.id)} className="rounded-lg border px-3 py-2 text-xs font-bold text-red-600">Cancelar</button>}</div></div></div>})}{!loading&&appointments.length===0&&<div className="rounded-2xl border bg-white p-8 text-center text-[#736f83]">Aún no tienes reservas.</div>}{loading&&<p className="rounded-2xl border bg-white p-8 text-center text-sm text-[#736f83]">Cargando reservas…</p>}</div></>
}
