'use client'
import { ModalShell } from '@/components/ModalShell'
import {PageHeader} from '@/components/PageHeader'
import {Check,Clock3,PhoneCall,Plus,UserPlus} from 'lucide-react'
import {FormEvent,useEffect,useState} from 'react'

type Client={id:string;full_name:string;phone?:string}
type Catalog={services:Array<{id:string;name:string}>;professionals:Array<{id:string;display_name:string}>}

export default function FollowupsPage(){
  const [data,setData]=useState<{tasks:any[];waitlist:any[]}>({tasks:[],waitlist:[]}),[clients,setClients]=useState<Client[]>([]),[catalog,setCatalog]=useState<Catalog>({services:[],professionals:[]}),[modal,setModal]=useState<'task'|'waitlist'|null>(null),[error,setError]=useState('')
  const load=()=>Promise.all([fetch('/api/admin/followups',{cache:'no-store'}),fetch('/api/admin/clients',{cache:'no-store'}),fetch('/api/admin/catalog',{cache:'no-store'})]).then(async([a,b,c])=>{if(!a.ok||!b.ok||!c.ok)throw new Error('No se pudo cargar el seguimiento');const [x,y,z]=await Promise.all([a.json(),b.json(),c.json()]);setData(x);setClients(y.clients??[]);setCatalog(z);setError('')}).catch(e=>setError(e.message))
  useEffect(()=>{load()},[])
  async function status(kind:'task'|'waitlist',id:string,next:string){const response=await fetch('/api/admin/followups',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({kind,id,status:next})});if(response.ok)load()}
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const response=await fetch('/api/admin/followups',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind:modal,clientId:form.get('clientId'),serviceId:form.get('serviceId'),professionalId:form.get('professionalId'),title:form.get('title'),notes:form.get('notes'),preferredFrom:form.get('preferredFrom')||null,preferredUntil:form.get('preferredUntil')||null})});if(response.ok){setModal(null);load()}else setError((await response.json()).error??'No se pudo guardar')}
  const pending=data.tasks.filter(item=>item.status==='PENDING'),waiting=data.waitlist.filter(item=>item.status==='WAITING')
  return <><PageHeader title="Seguimiento y lista de espera" description="Agen detecta ausencias y presupuestos pendientes para que ningún cliente se pierda." action={<div className="flex gap-2"><button onClick={()=>setModal('task')} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-bold"><Plus size={16}/>Tarea</button><button onClick={()=>setModal('waitlist')} className="inline-flex items-center gap-2 rounded-xl bg-[#5b3df5] px-4 py-2.5 text-sm font-bold text-white"><UserPlus size={16}/>Lista de espera</button></div>}/>{error&&<p className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border bg-white"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-extrabold">Qué hacer hoy</h2><p className="text-xs text-[#736f83]">Ausencias, presupuestos y tareas manuales.</p></div><span className="rounded-full bg-violet-100 px-3 py-1 text-xs font-bold text-[#5b3df5]">{pending.length}</span></div><div>{pending.map(item=><article key={item.id} className="flex items-start gap-3 border-b p-4"><PhoneCall className="mt-1 shrink-0 text-[#5b3df5]" size={18}/><div className="min-w-0 flex-1"><b className="text-sm">{item.title}</b><p className="text-sm text-[#736f83]">{item.client?.full_name} {item.client?.phone&&`· ${item.client.phone}`}</p><small className="text-[#9a96a5]">{item.reason.replaceAll('_',' ')}</small></div><button onClick={()=>status('task',item.id,'DONE')} className="rounded-lg bg-emerald-50 p-2 text-emerald-700" title="Completar"><Check size={17}/></button></article>)}{pending.length===0&&<p className="p-8 text-center text-sm text-[#736f83]">Todo está al día.</p>}</div></section>
      <section className="rounded-2xl border bg-white"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-extrabold">Esperando un cupo</h2><p className="text-xs text-[#736f83]">Clientes que desean un horario todavía no disponible.</p></div><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-700">{waiting.length}</span></div>{waiting.map(item=><article key={item.id} className="flex items-start gap-3 border-b p-4"><Clock3 className="mt-1 shrink-0 text-amber-600" size={18}/><div className="min-w-0 flex-1"><b className="text-sm">{item.client?.full_name}</b><p className="text-sm text-[#736f83]">{item.service?.name}{item.professional?.display_name&&` · ${item.professional.display_name}`}</p><small className="text-[#9a96a5]">{item.notes||'Sin observaciones'}</small></div><button onClick={()=>status('waitlist',item.id,'CONTACTED')} className="rounded-lg border px-3 py-2 text-xs font-bold">Contactado</button></article>)}{waiting.length===0&&<p className="p-8 text-center text-sm text-[#736f83]">No hay clientes esperando.</p>}</section></div>
    {modal&&<ModalShell titulo="Nueva tarea de seguimiento" onClose={()=>setModal(null)}><form onSubmit={create} className="w-full max-w-lg rounded-3xl bg-white p-6"><h2 className="text-xl font-black">{modal==='task'?'Nueva tarea':'Agregar a lista de espera'}</h2><div className="mt-5 grid gap-4"><label className="text-sm font-semibold">Cliente<select name="clientId" required className="mt-2 w-full rounded-xl border p-3"><option value="">Seleccionar</option>{clients.map(c=><option key={c.id} value={c.id}>{c.full_name}{c.phone?` · ${c.phone}`:''}</option>)}</select></label>{modal==='task'?<label className="text-sm font-semibold">Tarea<input name="title" required placeholder="Llamar para confirmar" className="mt-2 w-full rounded-xl border p-3"/></label>:<><label className="text-sm font-semibold">Servicio<select name="serviceId" required className="mt-2 w-full rounded-xl border p-3"><option value="">Seleccionar</option>{catalog.services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="text-sm font-semibold">Profesional preferido<select name="professionalId" className="mt-2 w-full rounded-xl border p-3"><option value="">Cualquiera compatible</option>{catalog.professionals.map(p=><option key={p.id} value={p.id}>{p.display_name}</option>)}</select></label></>}<label className="text-sm font-semibold">Notas<textarea name="notes" rows={3} className="mt-2 w-full rounded-xl border p-3"/></label></div><div className="mt-5 flex gap-3"><button type="button" onClick={()=>setModal(null)} className="flex-1 rounded-xl border py-3 font-bold">Cancelar</button><button className="flex-1 rounded-xl bg-[#5b3df5] py-3 font-bold text-white">Guardar</button></div></form></ModalShell>}</>
}
