'use client'
import { PageHeader } from '@/components/PageHeader'
import { NewProfessionalModal } from '@/components/NewProfessionalModal'
import { CalendarDays, Clock3, Plus } from 'lucide-react'
import { AvailabilityModal } from '@/components/AvailabilityModal'
import { useEffect, useState } from 'react'
import { TeamAgentContacts } from '@/components/TeamAgentContacts'
import { SpecialtyEditor } from '@/components/SpecialtyEditor'
type Professional={id:string;display_name:string;color:string;commission_percent:number;professional_specialties:Array<{specialty_id:string}>;professional_services:Array<{service_id:string;active:boolean}>}
export default function TeamPage(){const [items,setItems]=useState<Professional[]>([]),[specialties,setSpecialties]=useState<Array<{id:string;name:string}>>([]),[error,setError]=useState(false),[show,setShow]=useState(false),[schedule,setSchedule]=useState<{id:string;name:string}|null>(null);const load=()=>fetch('/api/admin/catalog').then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(d=>{setItems(d.professionals??[]);setSpecialties(d.specialties??[]);setError(false)}).catch(()=>setError(true));useEffect(()=>{load()},[]);return <>{show&&<NewProfessionalModal onClose={()=>setShow(false)} onCreated={load}/>}{schedule&&<AvailabilityModal professionalId={schedule.id} professionalName={schedule.name} onClose={()=>setSchedule(null)}/>}<PageHeader title="Equipo" description="Profesionales, especialidades, colores, horarios y comisiones." action={<button onClick={()=>setShow(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#5b3df5] px-4 py-2.5 text-sm font-bold text-white"><Plus size={17}/>Agregar profesional</button>}/>{error&&<p className="mb-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">Conecta Supabase para administrar el equipo.</p>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{items.map(p=>{const specialty=specialties.find(s=>s.id===p.professional_specialties?.[0]?.specialty_id)?.name??'Sin especialidad';return <article key={p.id} className="rounded-2xl border border-black/5 bg-white p-5 shadow-sm"><div className="flex items-center gap-4"><span className="grid h-14 w-14 place-items-center rounded-2xl text-lg font-black text-white" style={{background:p.color}}>{p.display_name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><h2 className="font-extrabold">{p.display_name}</h2><p className="text-sm text-[#736f83]">{specialty}</p></div></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-[#f6f5fa] p-3"><b>{p.professional_services?.filter(s=>s.active).length??0}</b><p className="text-xs text-[#736f83]">servicios</p></div><div className="rounded-xl bg-[#f6f5fa] p-3"><b>{p.commission_percent}%</b><p className="text-xs text-[#736f83]">comisión</p></div></div><div className="mt-4 grid grid-cols-2 gap-2"><a href={`/admin/agenda?professional=${p.id}`} className="flex items-center justify-center gap-2 rounded-xl border py-2 text-sm font-semibold"><CalendarDays size={16}/>Agenda</a><button type="button" onClick={()=>setSchedule({id:p.id,name:p.display_name})} className="flex items-center justify-center gap-2 rounded-xl border py-2 text-sm font-semibold"><Clock3 size={16}/>Horario</button></div></article>})}{!error&&items.length===0&&<p className="text-sm text-[#736f83]">Aún no hay profesionales.</p>}</div><SpecialtyEditor onChanged={load}/><TeamAgentContacts/></>}
