'use client'
import { PageHeader } from '@/components/PageHeader'
import { NewPortfolioModal } from '@/components/NewPortfolioModal'
import { Image as ImageIcon, Plus, Trash2 } from 'lucide-react'
import { useEffect, useState } from 'react'
type Item={id:string;title:string;after_url:string;published:boolean;client_consent:boolean;professional:{display_name:string}|null;service:{name:string}|null}
export default function GalleryPage(){const [items,setItems]=useState<Item[]>([]),[error,setError]=useState(false),[show,setShow]=useState(false);const load=()=>fetch('/api/admin/portfolio').then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(d=>{setItems(d.items??[]);setError(false)}).catch(()=>setError(true));useEffect(()=>{load()},[]);
  async function remove(item:Item){if(!window.confirm(`¿Eliminar "${item.title}" de la galería? No se puede deshacer.`))return;const response=await fetch(`/api/admin/portfolio?id=${item.id}`,{method:'DELETE'});if(response.ok)load();else setError(true)}
  async function togglePublished(item:Item){const response=await fetch('/api/admin/portfolio',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:item.id,changes:{published:!item.published}})});const data=await response.json().catch(()=>({}));if(response.ok)load();else window.alert(data.error??'No se pudo cambiar la publicación')}
  return <>{show&&<NewPortfolioModal onClose={()=>setShow(false)} onCreated={load}/>}<PageHeader title="Galería" description="Trabajos del equipo publicados solamente con autorización." action={<button onClick={()=>setShow(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#5b3df5] px-4 py-2.5 text-sm font-bold text-white"><Plus size={17}/>Subir trabajo</button>}/>{error&&<p className="mb-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">Conecta Supabase para administrar la galería.</p>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map(item=><article key={item.id} className="overflow-hidden rounded-2xl border bg-white"><div className="aspect-[4/3] bg-violet-50"><img src={item.after_url} alt={item.title} className="h-full w-full object-cover"/></div><div className="p-4"><b>{item.title}</b><p className="text-sm text-[#736f83]">{item.professional?.display_name} · {item.service?.name}</p><span className={`mt-2 inline-block rounded-full px-2 py-1 text-xs ${item.published?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{item.published?'Publicado':'Privado'}</span><div className="mt-3 flex gap-2"><button type="button" onClick={()=>togglePublished(item)} className="flex-1 rounded-lg border py-2 text-xs font-bold">{item.published?'Quitar de publicado':'Publicar'}</button><button type="button" aria-label="Eliminar trabajo" onClick={()=>remove(item)} className="rounded-lg border border-red-200 px-3 py-2 text-red-700"><Trash2 size={14}/></button></div>{!item.client_consent&&<p className="mt-2 text-xs text-[#736f83]">Sin autorización del cliente: no se puede publicar.</p>}</div></article>)}{!error&&items.length===0&&<div className="col-span-full rounded-2xl border bg-white p-8 text-center text-[#736f83]"><ImageIcon className="mx-auto mb-3 opacity-30"/>Aún no hay trabajos publicados.</div>}</div></>}
